frase = str('Curso em video python').lower()
print(frase)
print(frase[9], '= Índice 9')
print(frase[9:13], '= Índice do 9 ao 12, porém ele para no 12º caractere, um antes')
print(frase[9:21:2], '= Índice do 9 ao 21 pulando de 2 em 2 caracteres')
print(frase[:5], '= Do início ao índice 4')
print(frase[15:], '= Do caractere 15 ao final.')
print(frase[9: :3], '= Irá começar no índice 9 e vai até o final, pulando de 3 em 3 caractere.')
print(f'O comprimento da frase é de {len(frase)} caracteres')
letras = str(input('Qual letra você quer contar? ')).strip().lower()
print(f'A frase tem {frase.count(letras)} letras "{letras}"')
ind_ini = int(input('Digite a partir de qual índice você quer contar: '))
ind_fim = int(input('Qual é o índice final: '))
print(f'A partir do índice {ind_ini} até o índice {ind_fim} você tem {frase.count(letras, ind_ini, ind_fim)}'
      f' letra(s) "{letras}".')
print(f'O índice da letra {letras} é {frase.find(letras)}.')
print('android' in frase)